site_name: ChesslaBlab Website
site_url: https://chesslablab.github.io/website/
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - SSL Certificate Setup: ssl-certificate-setup.md
  - Website Architecture: website-architecture.md
