site_name: ChesslaBlab Website
site_url: https://chesslablab.github.io/website/
theme:
  name: readthedocs
nav:
  - Home: index.md
  - SSL Certificate Setup: ssl-certificate-setup.md
  - Installation: installation.md
  - Website Architecture: website-architecture.md
  - WebSocket Connection: websocket-connection.md
  - API Connection: api-connection.md
  - Blog: blog.md
