blog:
    path:       /{_locale}/blog
    controller: App\Controller\BlogController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de
    options:
      sitemap:
        _locale: en
      blog:
        metadata:
          title: ChesslaBlab Blog
          description: Here you will find a collection of your favorite topics. Open-source, chess, and more!

blog_hello_world:
    path:       /{_locale}/blog/hello-world
    controller: App\Controller\BlogController::entry
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de
    options:
      sitemap:
        _locale: en
      blog:
        metadata:
          title: Hello World!
          description: This is a simple static blog made with Symfony and Twig. The markdown_to_html filter is used to convert a block of Markdown to HTML.
        content:
          subtitle: Welcome to ChesslaBlab's blog
          image: hello-world.webp
          date: 09-05-2024

blog_getting_started:
    path:       /{_locale}/blog/getting-started
    controller: App\Controller\BlogController::entry
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de
    options:
      sitemap:
        _locale: en
      blog:
        metadata:
          title: Getting Started
          description: This is the second post just to make sure that the index page of the blog is set up properly.
        content:
          subtitle: This is the second example post
          image: getting-started.webp
          date: 12-05-2024
