# Setup routes
#
# These routes are intended for general-purpose setup. As a rule of thumb, any
# route that is not considered to be either a page or a blog post will fall into
# this category.

locale:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
      path: /en
      permanent: true

sitemap:
    path:       /sitemap.xml
    controller: App\Controller\SitemapController::index
    methods:    GET

robots:
    path:       /robots.txt
    controller: App\Controller\RobotsController::index
    methods:    GET

# Pages routes
#
# A page is intended for static content that is not updated as frequently as a
# blog post.

pages_database_event_stats:
    path:       /{_locale}/database/event-stats
    controller: App\Controller\Pages\Database\EventStatsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_database_player_stats:
    path:       /{_locale}/database/player-stats
    controller: App\Controller\Pages\Database\PlayerStatsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_database_search_games:
    path:       /{_locale}/database/search-games
    controller: App\Controller\Pages\Database\SearchGamesController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_database_top_openings:
    path:       /{_locale}/database/top-openings
    controller: App\Controller\Pages\Database\TopOpeningsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_edit:
    path:       /{_locale}/edit
    controller: App\Controller\Pages\EditController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_learn_annotated_games:
    path:       /{_locale}/learn/annotated-games
    controller: App\Controller\Pages\Learn\AnnotatedGamesController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_learn_classical:
    path:       /{_locale}/learn/classical
    controller: App\Controller\Pages\Learn\ClassicalController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_learn_fen_string:
    path:       /{_locale}/learn/fen-string
    controller: App\Controller\Pages\Learn\FenStringController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_learn_fischer_random:
    path:       /{_locale}/learn/fischer-random
    controller: App\Controller\Pages\Learn\FischerRandomController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_learn_rav_movetext:
    path:       /{_locale}/learn/rav-movetext
    controller: App\Controller\Pages\Learn\RavMovetextController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_learn_san_movetext:
    path:       /{_locale}/learn/san-movetext
    controller: App\Controller\Pages\Learn\SanMovetextController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_openings_eco_code:
    path:       /{_locale}/openings/eco-code
    controller: App\Controller\Pages\Openings\EcoCodeController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_openings_name:
    path:       /{_locale}/openings/name
    controller: App\Controller\Pages\Openings\NameController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_openings_san_movetext:
    path:       /{_locale}/openings/san-movetext
    controller: App\Controller\Pages\Openings\SanMovetextController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_play_computer:
    path:       /{_locale}/play/computer
    controller: App\Controller\Pages\Play\ComputerController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_play_online:
    path:       /{_locale}/
    controller: App\Controller\Pages\Play\OnlineController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr
    options:
      sitemap:
        _locale: en|es|fr|ru|tr

pages_players:
    path:       /{_locale}/players
    controller: App\Controller\Pages\PlayersController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_training_checkmate:
    path:       /{_locale}/training/checkmate
    controller: App\Controller\Pages\Training\CheckmateController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_training_endgame:
    path:       /{_locale}/training/endgame
    controller: App\Controller\Pages\Training\EndgameController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_settings:
    path:       /{_locale}/settings
    controller: App\Controller\Pages\Settings\SettingsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr

pages_about:
    path:       /{_locale}/about
    controller: App\Controller\Pages\AboutController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr
    options:
      sitemap:
        _locale: en

# Blog routes
#
# A post is intended for static content that may be updated more frequently as a
# blog post.

blog:
    path:       /{_locale}/blog
    controller: App\Controller\BlogController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr
    options:
      sitemap:
        _locale: en
      blog:
        metadata:
          title: ChesslaBlab Blog
          description: Here you will find a collection of your favorite topics. Open-source, chess, and more!

blog_hello_world:
    path:       /{_locale}/blog/hello-world
    controller: App\Controller\BlogController::hello_world
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr
    options:
      sitemap:
        _locale: en
      blog:
        metadata:
          title: Hello World!
          description: This is a simple static blog made with Symfony and Twig. The markdown_to_html filter is used to convert a block of Markdown to HTML.
        content:
          subtitle: Welcome to ChesslaBlab's blog
          image: hello-world.webp
          date: 09-05-2024

blog_getting_started:
    path:       /{_locale}/blog/getting-started
    controller: App\Controller\BlogController::getting_started
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr
    options:
      sitemap:
        _locale: en
      blog:
        metadata:
          title: Getting Started
          description: This is the second post just to make sure that the index page of the blog is set up properly.
        content:
          subtitle: This is the second example post
          image: getting-started.webp
          date: 12-05-2024
