pages_chessboard_classical:
    path:       /chessboard/classical
    controller: App\Controller\Pages\Chessboard\ClassicalController::index
    methods:    GET

pages_chessboard_fen_string:
    path:       /chessboard/fen-string
    controller: App\Controller\Pages\Chessboard\FenStringController::index
    methods:    GET

pages_chessboard_fischer_random:
    path:       /chessboard/fischer-random
    controller: App\Controller\Pages\Chessboard\FischerRandomController::index
    methods:    GET

pages_chessboard_san_movetext:
    path:       /chessboard/san-movetext
    controller: App\Controller\Pages\Chessboard\SanMovetextController::index
    methods:    GET

pages_database_annotated_games:
    path:       /database/annotated-games
    controller: App\Controller\Pages\Database\AnnotatedGamesController::index
    methods:    GET

pages_openings_eco_code:
    path:       /openings/eco-code
    controller: App\Controller\Pages\Openings\EcoCodeController::index
    methods:    GET

pages_openings_name:
    path:       /openings/name
    controller: App\Controller\Pages\Openings\NameController::index
    methods:    GET

pages_openings_san_movetext:
    path:       /openings/san-movetext
    controller: App\Controller\Pages\Openings\SanMovetextController::index
    methods:    GET

pages_play_friend_enter_invite_code:
    path:       /play/friend/enter-invite-code
    controller: App\Controller\Pages\Play\Friend\EnterInviteCodeController::index
    methods:    GET

pages_play_friend_index:
    path:       /play/friend
    controller: App\Controller\Pages\Play\Friend\IndexController::index
    methods:    GET

pages_play_computer:
    path:       /play/computer
    controller: App\Controller\Pages\Play\ComputerController::index
    methods:    GET

pages_play_online_create_game:
    path:       /play/online/create-game
    controller: App\Controller\Pages\Play\Online\CreateGameController::index
    methods:    GET

pages_play_online_index:
    path:       /
    controller: App\Controller\Pages\Play\Online\IndexController::index
    methods:    GET

pages_about:
    path:       /about
    controller: App\Controller\Pages\AboutController::index
    methods:    GET

pages_legal:
    path:       /legal
    controller: App\Controller\Pages\LegalController::index
    methods:    GET

pages_support:
    path:       /support
    controller: App\Controller\Pages\SupportController::index
    methods:    GET
