pages_learn_classical:
    path:       /learn/classical
    controller: App\Controller\Pages\Learn\ClassicalController::index
    methods:    GET

pages_learn_fen_string:
    path:       /learn/fen-string
    controller: App\Controller\Pages\Learn\FenStringController::index
    methods:    GET

pages_learn_fischer_random:
    path:       /learn/fischer-random
    controller: App\Controller\Pages\Learn\FischerRandomController::index
    methods:    GET

pages_learn_rav_movetext:
    path:       /learn/rav-movetext
    controller: App\Controller\Pages\Learn\RavMovetextController::index
    methods:    GET

pages_learn_san_movetext:
    path:       /learn/san-movetext
    controller: App\Controller\Pages\Learn\SanMovetextController::index
    methods:    GET

pages_learn_annotated_games:
    path:       /learn/annotated-games
    controller: App\Controller\Pages\Learn\AnnotatedGamesController::index
    methods:    GET

pages_database_search_games:
    path:       /database/search-games
    controller: App\Controller\Pages\Database\SearchGamesController::index
    methods:    GET

pages_database_top_openings:
    path:       /database/top-openings
    controller: App\Controller\Pages\Database\TopOpeningsController::index
    methods:    GET

pages_database_player_stats:
    path:       /database/player-stats
    controller: App\Controller\Pages\Database\PlayerStatsController::index
    methods:    GET

pages_openings_eco_code:
    path:       /openings/eco-code
    controller: App\Controller\Pages\Openings\EcoCodeController::index
    methods:    GET

pages_openings_name:
    path:       /openings/name
    controller: App\Controller\Pages\Openings\NameController::index
    methods:    GET

pages_openings_san_movetext:
    path:       /openings/san-movetext
    controller: App\Controller\Pages\Openings\SanMovetextController::index
    methods:    GET

pages_play_computer:
    path:       /play/computer
    controller: App\Controller\Pages\Play\ComputerController::index
    methods:    GET

pages_play_online:
    path:       /
    controller: App\Controller\Pages\Play\OnlineController::index
    methods:    GET

pages_about:
    path:       /about
    controller: App\Controller\Pages\AboutController::index
    methods:    GET

pages_legal:
    path:       /legal
    controller: App\Controller\Pages\LegalController::index
    methods:    GET

pages_support:
    path:       /support
    controller: App\Controller\Pages\SupportController::index
    methods:    GET
