routing_directory:
    resource: 'routing'
    type:     directory

# Setup routes

locale:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
      path: /en
      permanent: true

sitemap:
    path:       /sitemap.xml
    controller: App\Controller\SitemapController::index
    methods:    GET

robots:
    path:       /robots.txt
    controller: App\Controller\RobotsController::index
    methods:    GET

# Pages routes

pages_database_event_stats:
    path:       /{_locale}/database/event-stats
    controller: App\Controller\Pages\Database\EventStatsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_database_player_stats:
    path:       /{_locale}/database/player-stats
    controller: App\Controller\Pages\Database\PlayerStatsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_database_search_games:
    path:       /{_locale}/database/search-games
    controller: App\Controller\Pages\Database\SearchGamesController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_database_top_openings:
    path:       /{_locale}/database/top-openings
    controller: App\Controller\Pages\Database\TopOpeningsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_edit:
    path:       /{_locale}/edit
    controller: App\Controller\Pages\EditController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_learn_analysis:
    path:       /{_locale}/learn/analysis
    controller: App\Controller\Pages\Learn\AnalysisController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_learn_annotated_games:
    path:       /{_locale}/learn/annotated-games
    controller: App\Controller\Pages\Learn\AnnotatedGamesController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_learn_rav_movetext:
    path:       /{_locale}/learn/rav-movetext
    controller: App\Controller\Pages\Learn\RavMovetextController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_openings_eco_code:
    path:       /{_locale}/openings/eco-code
    controller: App\Controller\Pages\Openings\EcoCodeController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_openings_name:
    path:       /{_locale}/openings/name
    controller: App\Controller\Pages\Openings\NameController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_openings_san_movetext:
    path:       /{_locale}/openings/san-movetext
    controller: App\Controller\Pages\Openings\SanMovetextController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_play_computer:
    path:       /{_locale}/play/computer
    controller: App\Controller\Pages\Play\ComputerController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_play_online:
    path:       /{_locale}/
    controller: App\Controller\Pages\Play\OnlineController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi
    options:
      sitemap:
        _locale: en|es|fr|ru|tr|de|hi

pages_players:
    path:       /{_locale}/players
    controller: App\Controller\Pages\PlayersController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_training_checkmate:
    path:       /{_locale}/training/checkmate
    controller: App\Controller\Pages\Training\CheckmateController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_training_endgame:
    path:       /{_locale}/training/endgame
    controller: App\Controller\Pages\Training\EndgameController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_settings:
    path:       /{_locale}/settings
    controller: App\Controller\Pages\Settings\SettingsController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi

pages_about:
    path:       /{_locale}/about
    controller: App\Controller\Pages\AboutController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr|ru|tr|de|hi
    options:
      sitemap:
        _locale: en
