chessboard_classical:
    path:       /chessboard/classical
    controller: App\Controller\ChessboardController::classical
    methods:    GET

chessboard_fischer_random:
    path:       /chessboard/fischer-random
    controller: App\Controller\ChessboardController::fischerRandom
    methods:    GET

chessboard_san_movetext:
    path:       /chessboard/san-movetext
    controller: App\Controller\ChessboardController::sanMovetext
    methods:    GET

chessboard_fen_string:
    path:       /chessboard/fen-string
    controller: App\Controller\ChessboardController::fenString
    methods:    GET

play_computer:
    path:       /play/computer
    controller: App\Controller\PlayController::computer
    methods:    GET

openings_index:
    path:       /openings
    controller: App\Controller\OpeningsController::index
    methods:    GET
